// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkuKAUwZNSknr2M0KeqJ6F26QBHNT4l7k',
    appId: '1:931019713536:web:2045faed24f1af2dc5bce5',
    messagingSenderId: '931019713536',
    projectId: 'juru-5d489',
    authDomain: 'juru-5d489.firebaseapp.com',
    storageBucket: 'juru-5d489.firebasestorage.app',
    measurementId: 'G-FWE0R2S8YY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZgysz_QmyyZgVS-0X0DImWS_RzfnhYR4',
    appId: '1:931019713536:android:347d633beca224aac5bce5',
    messagingSenderId: '931019713536',
    projectId: 'juru-5d489',
    storageBucket: 'juru-5d489.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDp-thQMAhwlpQM5IgxBSHLoU11YaK8A_0',
    appId: '1:931019713536:ios:856396adbeacced4c5bce5',
    messagingSenderId: '931019713536',
    projectId: 'juru-5d489',
    storageBucket: 'juru-5d489.firebasestorage.app',
    iosBundleId: 'com.example.juruStay',
  );

}